[package]
name = "rustfuscator"
version = "0.2.0"
edition = "2024"
description = "A Rust library to easily obfuscate strings and control-flow using cryptify lib"
license = "MIT"
repository = "https://github.com/GianIac/rustfuscator"
categories = ["development-tools", "command-line-utilities", "cryptography"]

keywords = [
    "obfuscation",
    "macros",
    "security",
    "cli",
    "rust-tools"
]

[workspace]
members = [
    ".",                   
    "obfuscator_derive",  
    "obfuscator_cli",
]

[features]
obfuscation = []

[dependencies]
cryptify = "3.1.1"
rand = "0.8"
aes-gcm = "0.10"
aes = "0.8"
aead = "0.5"
obfuscator_derive = "0.2.0"
