[package]
name = "rust_code_obfuscator"
version = "0.1.0"
edition = "2024"
description = "A Rust library to easily obfuscate strings and control-flow using cryptify lib"
license = "MIT"
repository = "https://github.com/GianIac/rustfuscator"
categories = ["cryptography", "development-tools"]

[features]
obfuscation = []

[dependencies]
cryptify = "3.1.1"
rand = "0.8"