[package]
name = "obfuscator_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
walkdir = "2"
regex = "1"
anyhow = "1"

syn = { version = "2", features = ["full", "visit-mut"] }
quote = "1"
proc-macro2 = "1"
