[package]
name = "obfuscator_cli"
version = "0.2.7"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
walkdir = "2"
regex = "1"
anyhow = "1"

syn = { version = "2", features = ["full", "visit-mut"] }
quote = "1"
proc-macro2 = "1"
fs_extra = "1.2"
toml_edit = "0.23.1"
toml = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
globset = "0.4"
serde_json = "1.0"
cargo_metadata = "0.21.0"

rust_code_obfuscator_core = { path = "../rust_code_obfuscator_core" }